import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import SideBar from '@/components/SideBar'
import SessionProvider from '@/components/SessionProvider'
import { getServerSession } from 'next-auth'
//import {authOptions} from './api/auth/[...nextauth]/route'
import Login from '@/components/Login'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import ClientProvider from '@/components/ClientProvider'
import { useEffect} from 'react'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const session = await getServerSession(authOptions)
    // console.log(session)
    // const [selectedChampion, setSelectedChampion] = useState('')
    const handleSelection = (championData: string) => {
        // setSelectedChampion(championData)
    }


  return (
    <html lang="en">
      <head>
      <title>LOLChat</title>
        <meta content='width=device-width, initial-scale=1'
          name='viewport' 
        />
        <link rel='icon' href='/favicon.ico'/>
      </head>

      <body>
        <SessionProvider session={session}>
          {!session ? (
            <Login/>
          ) : (
            <div className="flex flex-row">
            {/*Sidebar*/}
            <SideBar/>
            <ClientProvider/>

            <div className="bg-black">
                {/* <img src='/champions/Aatrox/background/Aatrox_OriginalSkin.jpg' className='w-full h-full object-cover'/> */}
                {children}
            </div>
            </div>
          )}            
        </SessionProvider>
      </body>
    </html>
  )
}
