import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import SideBar from "@/components/SideBar";
import SessionProvider from "@/components/SessionProvider";
import { getServerSession } from "next-auth";
//import {authOptions} from './api/auth/[...nextauth]/route'
import Login from "@/components/Login";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import ClientProvider from "@/components/ClientProvider";
import { useEffect } from "react";
import pattern from "../public/styles/63171.jpg";
import Image from "next/image";
import {StateProvider} from '../components/StateContext'
import GoogleAnalytics from './GoogleAnalytics'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <head>
      
<script async src="https://www.googletagmanager.com/gtag/js?id=G-S1Y6H7QQ2M"></script>
        <title>LOLChatAI</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="title" content="LOLChatAI"></meta>

        <meta name="google-adsense-account" content="ca-pub-4323342789576939"></meta>
        <link
          href="https://fonts.googleapis.com/css2?family=Teko:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" type="image/png" href="/Default_midnight_green_logo_for_chatbot_company_with_two_scary_1_83ccea56-f15d-494b-b825-9d264bd0c50d_0.png" />
      </head>

      <body className="bg-black">
        <GoogleAnalytics/>
        <SessionProvider session={session}>
            <StateProvider>
            {!session ? (
                <>
                <Login />
                </>
            ) : (
                <div className="flex flex-row fullHeight">
                {/*Sidebar*/}
                <SideBar />
                <ClientProvider />

                <div className="bg-black">
                    {children}
                </div>
                </div>
            )}
            </StateProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
